# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  run_tests_export:
    working_directory: ~/espnet_onnx
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo apt-get -y update
      - run: pip install --upgrade pip
      - run: pip install -r tools/requirements_export.txt
      - run: pip install pytest
      # - run: pytest tests/test_export.py --config_dir tests/test_config

workflows:
  build_and_test:
    jobs:
      - run_tests_export
